build: Ensure plugins see the generated Wayland protocols
With plugins using more parts of phosh they need access to the
protocol headers as well as these are used by e.g. PhoshMonitor.

This fixes compilation failures when building plugins like

  In file included from ../src/monitor/monitor.h:11,
                   from ../src/monitor-manager.h:11,
                   from ../src/plugin-shell.h:12,
                   from ../plugins/caffeine-quick-setting/caffeine-quick-setting.c:10:
  ../src/phosh-wayland.h:10:10: fatal error: ext-idle-notify-v1-client-protocol.h: No such file or directory
     10 | #include "ext-idle-notify-v1-client-protocol.h"
        |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Guido Günther <agx@sigxcpu.org>
Part-of: <https://gitlab.gnome.org/World/Phosh/phosh/-/merge_requests/1426>