build: Drop tags generation
Otherwise meson 0.53 fails with

```
ERROR: Multiple producers for Ninja target "TAGS". Please rename your targets.
```

since it has tags support build in.

Signed-off-by: Guido Günther <guido.gunther@puri.sm>