build: Drop -DHAVE_CONFIG.H
We build a phosh-config.h and hence defining this would just
include random other config.h from other projects. E.g.

   plugins/upcoming-events/phosh-plugin-upcoming-events-gnome-shell-calendar-dbus.c:10:12: fatal error: config.h: No such file or directory
   10 | #  include "config.h"
      |            ^~~~~~~~

Fixes b5b03b0c0 ("build: Rename config.h to phosh-config.h")

Signed-off-by: Guido Günther <guido.gunther@puri.sm>