build: Declare gio-unix-2.0 dep where necessary
The launcher-box and ticket-box plugin meson files didn't declare a
dependency on gio-unix-2.0.

This can cause the build to fail with an error like:

    ../plugins/launcher-box/launcher-row.h:12:10: fatal error: gio/gdesktopappinfo.h: No such file or directory
       12 | #include <gio/gdesktopappinfo.h>
          |          ^~~~~~~~~~~~~~~~~~~~~~~

Part-of: <https://gitlab.gnome.org/World/Phosh/phosh/-/merge_requests/1363>